name : build and push docker image 

on : 
  push : 
    branches : 
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v3


      - name: log in docker hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .

      - name : push docker image 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest